version = 0.1
[default.deploy.parameters]
stack_name = "circuit-cv-api"
resolve_s3 = true
s3_prefix = "circuit-cv-api"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
